# Installing the all Packages

In [1]:
!pip3 install pandas numpy seaborn matplotlib sklearn

  Using cached pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-

In [4]:
!pip3 install pandas

  Using cached pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]


In [9]:
!pip3 install matplotlib seaborn scikit-learn

  Using cached matplotlib-3.10.9-cp313-cp313-win_amd64.whl.metadata (52 kB)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl.metadata (119 kB)
  Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
  Using cached pillow-12.2.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -- -----

# Code Starts

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, roc_auc_score


In [3]:
data = {
    'wbc_count':     [11,4,13,3,15,9,5,14,3,12,10,4,13,6,14,3,8,15,4,11],
    'fever_days':    [3,0,5,0,7,1,0,6,0,4,2,0,5,0,6,0,1,7,0,3],
    'crp_level':     [45,8,80,5,120,15,7,95,4,60,30,6,85,9,110,5,12,130,6,50],
    'infected':      [1,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1]
}

df = pd.DataFrame(data)

df.head()
print(f"total patients :- {len(df)}")
print(f'Infected people (1):- {df['infected'].sum()}')
print(f'Non - Infected people (0):- {(df['infected'] == 0).sum()}')


total patients :- 20
Infected people (1):- 9
Non - Infected people (0):- 11


In [4]:
df.head()

,wbc_count,fever_days,crp_level,infected
0,11,3,45,1
1,4,0,8,0
2,13,5,80,1
3,3,0,5,0
4,15,7,120,1


In [22]:
# Train_Test_Splitting

x = df.drop(['infected'], axis=1)
y = df['infected']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)


# Scaling after splitting
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

# Model Training
model = LogisticRegression()

model.fit(X_train_s, y_train)

# Prediction time
y_pred = model.predict(X_test_s)
y_proba = model.predict_proba(X_test_s)

# print(y_proba)

print("Actual   :", list(y_test))
print("Predicted:", list(y_pred))
print(f"Probability of infection:\n { y_proba}")


Actual   : [0, 1, 0, 1, 1, 0]
Predicted: [np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(0)]
Probability of infection:
 [[0.92286503 0.07713497]
 [0.00955399 0.99044601]
 [0.94890073 0.05109927]
 [0.20833026 0.79166974]
 [0.03647986 0.96352014]
 [0.93779525 0.06220475]]


In [23]:
from sklearn.metrics import confusion_matrix

con_mat = confusion_matrix(y_test, y_pred)

print(con_mat)

[[3 0]
 [0 3]]


In [26]:
# TN = con_mat[0,0]
# FP = con_mat[0,1]
# FN = con_mat[1,0]
# TP = con_mat[1,1]

# accuracy = (TN + TP) / (TN+TP+FP+FN)
# print(accuracy)

In [21]:
from sklearn.metrics import classification_report
metrics_scores = classification_report(y_test, y_pred)

print(metrics_scores)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [57]:
num = 0.3
y_proba_new = y_proba[:,1]
y_pred_new = (y_proba_new>=num).astype(int)


recall_2 = recall_score(y_test, y_pred_new)

con_mat_new = confusion_matrix(y_test , y_pred_new)

print(con_mat_new)
print(y_pred_new) 
print(recall_2)

[[3 0]
 [0 3]]
[0 1 0 1 1 0]
1.0


In [58]:
accuracy = accuracy_score(y_test , y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(accuracy)
print(precision)
print(recall)
print(f1)

# Custom threshold below 0.5
threshold = 0.3
y_pred_custom = (y_proba[:,1] >= threshold).astype(int)
print(y_pred_custom)

recall_custom = recall_score(y_test, y_pred_custom)
print(recall)
print(recall_custom)

1.0
1.0
1.0
1.0
[0 1 0 1 1 0]
1.0
1.0
